name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    name: Discover charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build matrix from charts/* containing Chart.yaml
        id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          # Find all chart directories containing a Chart.yaml (e.g., charts/immich)
          mapfile -t dirs < <(find charts -mindepth 1 -maxdepth 2 -type f -name Chart.yaml -print0 | xargs -0 -n1 dirname | sort -u)
          json='{"include":['
          first=1
          for d in "${dirs[@]}"; do
            if [[ $first -eq 1 ]]; then first=0; else json+=","; fi
            json+="{\"working-directory\":\"$d\"}"
          done
          json+="]}"
          echo "matrix=$json" >> "$GITHUB_OUTPUT"
          echo "Discovered charts matrix: $json"

  unit:
    name: Helm Chart Unit Tests
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          # renovate: datasource=github-releases depName=helm/helm
          version: v3.18.6

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run Helm chart unit tests
        working-directory: ${{ matrix.working-directory }}
        run: |
          helm unittest -f "templates/tests/**/*.yaml" .
